apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: imdblistanalyzer
  labels:
    app: imdblistanalyzer

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: imdblistanalyzer

  template:
    metadata:
      labels:
        app: imdblistanalyzer
      annotations:
    spec:
      containers:
        - image: gcr.io/imdblistanalyzer/imdb-to-kube:latest
          name: imdblistanalyzer
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool