kind: Service
apiVersion: v1
metadata:
  labels:
    app: imdblistanalyzer
  name: my-test-cluster
  namespace: imdb

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: imdblistanalyzer
