FROM clojure:openjdk-11-lein as builder
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN lein uberjar

FROM openjdk:11-jre-stretch
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/target/imdb-list-analyzer-standalone.jar ./target/
COPY --from=builder /usr/src/app/resources/ ./resources/
ENV JAVA_OPTS='-XX:+UseContainerSupport -Xmx300m -Xss512k'
ENV PORT=8080
EXPOSE $PORT
CMD java $JAVA_OPTS -jar ./target/imdb-list-analyzer-standalone.jar $PORT
