apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: imdb
  name: imdb-list-analyzer
  labels:
    app: imdb-list-analyzer

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: imdb-list-analyzer

  template:
    metadata:
      labels:
        app: imdb-list-analyzer
      annotations:
    spec:
      containers:
        - image: gcr.io/imdb-list-analyzer/imdb-list-analyzer:develop
          name: imdb-list-analyzer
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        cloud.google.com/gke-nodepool: workshop-pool