kind: Service
apiVersion: v1
metadata:
  labels:
    app: tomi-imdb-list-analyzer
  name: tomi-imdb-list-analyzer
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tomi-imdb-list-analyzer