apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ${gke_namespace}
  name: ${project_id}
  labels:
    app: ${project_id}

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: ${project_id}

  template:
    metadata:
      labels:
        app: ${project_id}
      annotations:
    spec:
      containers:
        - image: ${repo_name}:latest
          name: ${project_id}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool