kind: Service
apiVersion: v1
metadata:
  labels:
    app: ${project_id}
  name: ${project_id}
  namespace: ${gke_namespace}

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ${project_id}
